{% set name = "pyflakes" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05a85c2872edf37a4ed30b0cce2f6093e1d0581f8c19d7393122da7e25b2b24c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyflakes = pyflakes.api:main


requirements:
  host:
    - python =2.7|>=3.5
    - pip
  run:
    - python =2.7|>=3.5

test:
  imports:
    - pyflakes
    - pyflakes.scripts
  commands:
    - pip check
    - pyflakes --help
  requires:
    - pip


about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pyflakes analyzes programs and detects various errors.
  dev_url: https://github.com/PyCQA/pyflakes

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
