travis:
  secure:
    BINSTAR_TOKEN: oj/OjBO1/waix3pAPaw7E4vhfHtAv/bbNWIjEkUkKADCf56H9ShbzKywe7DNB5z5mCesgBHsc6Hi447fhSb/gSVDlEhRsQwg+nNs4BHeuZVHju1K6YutKM/w07Hi+9A2vB230SQPzZTup5I3mBZWDED8Dxdh5Q8iMSvUZw1AFoE7+aLF9/Pnu+bBL7pGGnodL8v7uw2lKTdkeywRbLkuCk/ieRhhO2sL0hf9xfxUbayz8i5OPFUU4yyh8E2CtD716OrRmPkFIHa4K9cfuM831r5srpZ68Peg+vdIwN+vAqxAKfb++hMMfdhYXleLilkjzSSmkzZ+rovmmchnSC8PLOJ4GqNKvWM0MoKQbFQ2lud9e1uX9Tpe7HG55MYVnCXomnCWagcbfgCSDgcWtuUJq6rciga9bCRYYZD7oz5OUpjAVOU+IW5hp6u/mtZ8QGnJzbdnU4wgiLh9jb2VyWa2B1ODq5xi7jsn1WF49VvChcDn7xuSR1QMPk9GYtCyCngvBpANhxCP1VWUHAcYPvPhrvBIpgX5f5D/wwaGR/HRrsknSTkOL0puLN7CxxHDjOeediI3wQfdMgPkyOJhxbaQxX95jA9yFNvHBL7ZFUB/oxtaejSUggKv4OqQ4EmbjC6ZCerLcq/2e4VbJ17fCQ553BbhAD+l0SjRUW2nXr8sY7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
